resource_types:
- name: ubuntu
  type: docker-image
  source:
    repository: docker.prod.pdc.digital.csaa-insurance.aaa.com/ruby-rbvmomi
    tag: latest


jobs:
- name: sandbox_esx_stats
  plan:
  - get: vmware-stats-repo
    trigger: true
  - get: 15m
    trigger: true
  - task: vmware-stats-to-datadog
    file: vmware-stats-repo/ci/tasks/get_esx_info/task.yml
    params:
      DATADOG_API_KEY: {{datadog_api_key}}
      ESX_HOST: {{sandbox_esx_host}}
      ESX_USER: {{sandbox_esx_user}}
      ESX_PASSWORD: {{sandbox_esx_password}}
      ESX_DATACENTER: {{sandbox_esx_datacenter}}
      PCF_TAG: {{sandbox_pcf_tag}}
      DATASTORES: {{sandbox_datastores}}

- name: gdc_esx_stats
  plan:
  - get: vmware-stats-repo
    trigger: true
  - get: 15m
    trigger: true
  - task: vmware-stats-to-datadog
    file: vmware-stats-repo/ci/tasks/get_esx_info/task.yml
    params:
      DATADOG_API_KEY: {{datadog_api_key}}
      ESX_HOST: {{gdc_esx_host}}
      ESX_USER: {{gdc_esx_user}}
      ESX_PASSWORD: {{gdc_esx_password}}
      ESX_DATACENTER: {{gdc_esx_datacenter}}
      PCF_TAG: {{gdc_pcf_tag}}
      DATASTORES: {{gdc_datastores}}

- name: pdc_esx_stats
  plan:
  - get: vmware-stats-repo
    trigger: true
  - get: 15m
    trigger: true
  - task: vmware-stats-to-datadog
    file: vmware-stats-repo/ci/tasks/get_esx_info/task.yml
    params:
      DATADOG_API_KEY: {{datadog_api_key}}
      ESX_HOST: {{pdc_esx_host}}
      ESX_USER: {{pdc_esx_user}}
      ESX_PASSWORD: {{pdc_esx_password}}
      ESX_DATACENTER: {{pdc_esx_datacenter}}
      PCF_TAG: {{pdc_pcf_tag}}
      DATASTORES: {{pdc_datastores}}

resources:
- name: vmware-stats-repo
  type: git
  source:
    uri: ssh://git@ssh.github.com:443/aaa-ncnu-ie/vmware_stats.git
    branch: master
    private_key: {{github_private_key}}
- name: 15m
  type: time
  source: {interval: 15m}
