---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: docker.prod.pdc.digital.csaa-insurance.aaa.com/ruby-rbvmomi
    tag: latest

inputs:
  - name: vmware-stats-repo

run:
  path: vmware-stats-repo/ci/tasks/get_esx_info/vmware-metrics.rb

params:
  params:
    DATADOG_API_KEY:
    SANDBOX_ESX_HOST:
    SANDBOX_ESX_USER:
    SANDBOX_ESX_PASSWORD:
