---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: docker.prod.pdc.digital.csaa-insurance.aaa.com/ubuntu-ruby-aws
    tag: latest

inputs:
  - name: digital-ssl-status-repo

run:
  path: digital-ssl-status-repo/ci/tasks/get_ssl_info/get_cert_status.rb

params:
  params:
    OPSMAN_USERNAME:
    OPSMAN_PASSWORD:
    OPSMAN_URI:
